create table if not exists public.waitlist (
  id uuid primary key,
  name text not null,
  email text not null unique,
  message text not null default '',
  source text not null default 'homepage',
  waitlist_number bigint generated by default as identity unique,
  status text not null default 'waiting',
  marketing_consent boolean not null default false,
  consent_at timestamptz,
  email_status text not null default 'not_configured',
  created_at timestamptz not null default now()
);

alter table public.waitlist
  add column if not exists waitlist_number bigint generated by default as identity,
  add column if not exists status text not null default 'waiting',
  add column if not exists marketing_consent boolean not null default false,
  add column if not exists consent_at timestamptz,
  add column if not exists email_status text not null default 'not_configured';

create unique index if not exists waitlist_number_unique_idx
  on public.waitlist (waitlist_number);

alter table public.waitlist enable row level security;

create index if not exists waitlist_created_at_idx
  on public.waitlist (created_at desc);
